apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hellowhale
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/vamsijakkula/fluxcd

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hellowhale
  namespace: flux-system
spec:
  interval: 1m
  path: ./deploy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: hellowhale
  targetNamespace: default
  timeout: 3m0s
  wait: true
